name: プレビューURLコメント
on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const { ref } = context.payload.pull_request.head
            const pullNumber = ref.replace(/refs\/pull\/(.*)\/merge/, '$1')

            github.issues.createComment({
              ...context.issue,
              body: `このPull Requestのプレビューは以下のURLでご確認ください。\n\n> http://gh-actions-pr-preview.s3-website-ap-northeast-1.amazonaws.com/${pullNumber}`
            })
